import 'dart:io';
import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;
import '../config.dart';
import '../generators/manifest_generator.dart';
import '../utils/log.dart';
import 'command_utils.dart';
import 'generate_command.dart';

/// One-time initialisation: generates the template manifest, wrapper script,
/// and `.gitignore`, then immediately runs `generate` to populate `generated/`.
class InitCommand extends Command<void> {
  @override
  final name = 'init';
  @override
  final description = 'Generate the Flatpak template manifest, wrapper script, '
      'and .gitignore on first run. '
      'Runs generate immediately after to populate generated/.';

  InitCommand() {
    argParser
      ..addOption('config',
          abbr: 'c', help: 'Config file path.', defaultsTo: 'flutpak.yaml')
      ..addOption('flutter',
          abbr: 'f',
          help: 'Flutter SDK git ref (tag, branch, or commit SHA). '
              'Overrides flutter.ref from config.')
      ..addFlag('force', help: 'Overwrite existing template files.')
      ..addFlag('no-foreign-deps',
          help: 'Skip foreign deps registry fetch (offline/air-gapped use).');
  }

  @override
  Future<void> run() async {
    final configPath = p.absolute(argResults!['config'] as String);
    final configDir = p.dirname(configPath);
    final cfg = FlatpakGenConfig.load(configPath, configDir);
    final flutterArg = argResults!['flutter'] as String?;
    final flutterRef = flutterArg ?? cfg.flutterRef;
    final force = argResults!['force'] as bool;
    final noForeignDeps = argResults!['no-foreign-deps'] as bool;

    final manifestCfg = cfg.manifest;
    if (manifestCfg == null) {
      logError('manifest section required in config for init');
      exit(1);
    }

    final outputDir = p.absolute(p.join(configDir, cfg.output));
    final appName = manifestCfg.appId.split('.').last;
    final templatePath = p.join(outputDir, '${manifestCfg.appId}.yml');

    if (File(templatePath).existsSync() && !force) {
      logError('$templatePath already exists. Use --force to overwrite.');
      exit(1);
    }

    validateManifestAssets(cfg, manifestCfg.appId, baseDir: configDir);

    String? resolvedRepoUrl = cfg.repoUrl;
    if (resolvedRepoUrl == null) {
      final result = Process.runSync('git', ['remote', 'get-url', 'origin']);
      if (result.exitCode == 0) {
        resolvedRepoUrl = (result.stdout as String).trim();
        logWarn('repo-url not set — using "$resolvedRepoUrl" '
            '(from git remote origin); set repo-url explicitly to override');
      }
    }

    if (manifestCfg.commandInferred) {
      logWarn('manifest.command not set — using "${manifestCfg.command}" '
          '(last segment of app-id); set manifest.command explicitly to override');
    }

    final hasFlutter = flutterRef != null;
    final sourcesPath = p.join(outputDir, 'generated', 'pubspec-sources.json');
    final generator = ManifestGenerator(
      cfg: manifestCfg,
      generatedSourcesPath: sourcesPath,
      outputRelDir: cfg.output,
      resolvedRepoUrl: resolvedRepoUrl,
      hasFlutter: hasFlutter,
      metainfoPath: cfg.effectiveMetainfoPath(manifestCfg.appId),
      desktopEntryPath: cfg.effectiveDesktopEntryPath(manifestCfg.appId),
      icons: cfg.effectiveIcons(manifestCfg.appId),
      disableSubmodules: cfg.disableSubmodules,
    );
    final templateFile = File(templatePath)..createSync(recursive: true);
    templateFile.writeAsStringSync(generator.generate());
    logInfo('✓  template created: $templatePath');

    if (hasFlutter) {
      final wrapperPath = p.join(outputDir, '$appName-wrapper.sh');
      if (!File(wrapperPath).existsSync() || force) {
        File(wrapperPath)
          ..createSync(recursive: true)
          ..writeAsStringSync(
            '#!/bin/sh\n'
            '# Generated by flutpak — https://github.com/o-murphy/flutpak\n'
            'APP=/app/$appName\n'
            'export LD_LIBRARY_PATH="\$APP/lib:\${LD_LIBRARY_PATH:-}"\n'
            'exec "\$APP/${manifestCfg.command}" "\$@"\n',
          );
        logInfo('✓  wrapper created: $wrapperPath');
      }
    }

    final gitignorePath = p.join(outputDir, '.gitignore');
    if (!File(gitignorePath).existsSync() || force) {
      File(gitignorePath)
        ..createSync(recursive: true)
        ..writeAsStringSync(
          '# Generated by flutpak — https://github.com/o-murphy/flutpak\n'
          'generated/\n',
        );
      logInfo('✓  .gitignore created: $gitignorePath');
    }

    stderr.writeln('');
    logInfo('Running generate...');
    final generateCmd = GenerateCommand();
    await generateCmd.runWithArgs(
      cfg: cfg,
      baseDir: configDir,
      tagArg: null,
      commitArg: null,
      flutterRefOverride: flutterArg,
      noForeignDeps: noForeignDeps,
      outputDir: outputDir,
    );
  }
}
