import 'dart:io';
import 'package:args/command_runner.dart';
import 'package:path/path.dart' as p;
import '../config.dart';
import '../generators/manifest_generator.dart';
import 'command_utils.dart';
import 'generate_command.dart';

/// One-time initialisation: generates the template manifest, wrapper script,
/// `flathub.json`, and `.gitignore`, then immediately runs `generate` to
/// populate `generated/`.
class InitCommand extends Command<void> {
  @override
  final name = 'init';
  @override
  final description = 'Generate the Flatpak template manifest, wrapper script, '
      'flathub.json, and .gitignore on first run. '
      'Runs generate immediately after to populate generated/.';

  InitCommand() {
    argParser
      ..addOption('config',
          abbr: 'c', help: 'Config file path.', defaultsTo: 'flutpak.yaml')
      ..addOption('sdk',
          abbr: 's', help: 'Flutter SDK path. Defaults to \$FLUTTER_ROOT.')
      ..addFlag('force', abbr: 'f', help: 'Overwrite existing template files.');
  }

  @override
  Future<void> run() async {
    final configPath = argResults!['config'] as String;
    final configDir = p.dirname(p.absolute(configPath));
    final cfg = FlatpakGenConfig.load(configPath, configDir);
    final sdkPath = argResults!['sdk'] as String? ??
        cfg.flutterSdk ??
        Platform.environment['FLUTTER_ROOT'];
    final force = argResults!['force'] as bool;

    final manifestCfg = cfg.manifest;
    if (manifestCfg == null) {
      stderr.writeln('error: manifest section required in config for init');
      exit(1);
    }

    final outputDir = p.absolute(cfg.output);
    final appName = manifestCfg.appId.split('.').last;
    final templatePath = p.join(outputDir, '${manifestCfg.appId}.yml');

    // Check template doesn't already exist.
    if (File(templatePath).existsSync() && !force) {
      stderr.writeln(
          'error: $templatePath already exists. Use --force to overwrite.');
      exit(1);
    }

    // Validate asset files exist.
    validateManifestAssets(cfg, manifestCfg.appId);

    // Auto-detect repo URL.
    String? resolvedRepoUrl = cfg.repoUrl;
    if (resolvedRepoUrl == null) {
      final result = Process.runSync('git', ['remote', 'get-url', 'origin']);
      if (result.exitCode == 0) {
        resolvedRepoUrl = (result.stdout as String).trim();
        stderr.writeln('ℹ  repo-url not set — using "$resolvedRepoUrl" '
            '(from git remote origin); set repo-url explicitly to override');
      }
    }

    if (manifestCfg.commandInferred) {
      stderr.writeln(
          'ℹ  manifest.command not set — using "${manifestCfg.command}" '
          '(last segment of app-id); set manifest.command explicitly to override');
    }

    // Generate template manifest (patches are injected at generate time,
    // not baked into the template, so versions stay in sync with pubspec.lock).
    final hasFlutter = sdkPath != null;
    final sourcesPath =
        p.join(outputDir, 'generated', 'generated-sources.json');
    final generator = ManifestGenerator(
      cfg: manifestCfg,
      generatedSourcesPath: sourcesPath,
      outputRelDir: cfg.output,
      resolvedRepoUrl: resolvedRepoUrl,
      hasFlutter: hasFlutter,
      metainfoPath: cfg.effectiveMetainfoPath(manifestCfg.appId),
      desktopEntryPath: cfg.effectiveDesktopEntryPath(manifestCfg.appId),
      icons: cfg.effectiveIcons(manifestCfg.appId),
    );
    final templateFile = File(templatePath)..createSync(recursive: true);
    templateFile.writeAsStringSync(generator.generate());
    stderr.writeln('✓  template created: $templatePath');

    // Generate wrapper.sh (only for Flutter projects).
    if (hasFlutter) {
      final wrapperPath = p.join(outputDir, '$appName-wrapper.sh');
      if (!File(wrapperPath).existsSync() || force) {
        File(wrapperPath)
          ..createSync(recursive: true)
          ..writeAsStringSync(
            '#!/bin/sh\n'
            '# Generated by flutpak — https://github.com/o-murphy/flutpak\n'
            'APP=/app/$appName\n'
            'export LD_LIBRARY_PATH="\$APP/lib:\${LD_LIBRARY_PATH:-}"\n'
            'exec "\$APP/$appName" "\$@"\n',
          );
        stderr.writeln('✓  wrapper created: $wrapperPath');
      }
    }

    // Generate flathub.json.
    final flathubPath = p.join(outputDir, 'flathub.json');
    if (!File(flathubPath).existsSync() || force) {
      File(flathubPath)
        ..createSync(recursive: true)
        ..writeAsStringSync('{\n  "skip-appstream-check": false\n}\n');
      stderr.writeln('✓  flathub.json created: $flathubPath');
    }

    // Generate .gitignore.
    final gitignorePath = p.join(outputDir, '.gitignore');
    if (!File(gitignorePath).existsSync() || force) {
      File(gitignorePath)
        ..createSync(recursive: true)
        ..writeAsStringSync(
          '# Generated by flutpak — https://github.com/o-murphy/flutpak\n'
          'generated/\n',
        );
      stderr.writeln('✓  .gitignore created: $gitignorePath');
    }

    // Run generate immediately.
    stderr.writeln('');
    stderr.writeln('Running generate...');
    final generateCmd = GenerateCommand();
    await generateCmd.runWithArgs(
      cfg: cfg,
      sdkPath: sdkPath,
      tagArg: null,
      commitArg: null,
      noSources: false,
      pubOnly: false,
      flutterOnly: false,
      outputDir: outputDir,
    );
  }
}
