import 'dart:io';
import 'package:path/path.dart' as p;
import '../config.dart';

const String tagPlaceholder = '__FLATPAK_TAG__';
const String commitPlaceholder = '__FLATPAK_COMMIT__';

/// Generates a Flatpak application manifest YAML from [ManifestConfig].
///
/// Writes a human-readable manifest file using a structured template.
/// Multi-line build commands use YAML block scalar (`|`) notation.
class ManifestGenerator {
  final ManifestConfig cfg;

  /// Path to generated-sources.json relative to the project root.
  final String generatedSourcesPath;

  /// Directory path relative to the project source root used in install
  /// commands (e.g. `flatpak`). Defaults to `flatpak`.
  final String outputRelDir;

  /// Resolved git remote URL — overrides [ManifestConfig.repoUrl] when set.
  final String? resolvedRepoUrl;

  /// Whether this project uses Flutter. When false, Flutter-specific build
  /// commands (cache stamps, setup-flutter.sh, flutter build) are omitted and
  /// replaced with a TODO comment. Defaults to true for backward compatibility.
  final bool hasFlutter;

  ManifestGenerator({
    required this.cfg,
    required this.generatedSourcesPath,
    this.outputRelDir = 'flatpak',
    this.resolvedRepoUrl,
    this.hasFlutter = true,
  });

  /// Returns the manifest as a YAML string ready to write to disk.
  String generate() {
    final appName = cfg.appId.split('.').last;
    final buf = StringBuffer();

    _line(buf, '# Generated by flutpak — https://github.com/o-murphy/flutpak');
    _line(buf, '#');
    _line(buf, '# This is your editable TEMPLATE manifest — commit it to git.');
    _line(buf,
        '# Run "flutpak generate" on every build to produce the final output in generated/.');
    _line(buf, '#');
    _line(buf,
        '# SAFE TO EDIT   finish-args, build-commands, build-options, sdk-extensions, modules');
    _line(buf,
        '# DO NOT REMOVE  __FLATPAK_TAG__ and __FLATPAK_COMMIT__ placeholders — required by generate');
    _line(buf,
        '# AUTO-INJECTED  patch sources are appended after generated-sources.json by generate');
    _line(buf, 'app-id: ${cfg.appId}');
    _line(buf, 'runtime: org.freedesktop.Platform');
    _line(buf, "runtime-version: '${cfg.runtimeVersion}'");
    _line(buf, 'sdk: org.freedesktop.Sdk');

    if (cfg.sdkExtensions.isNotEmpty) {
      _line(buf, 'sdk-extensions:');
      for (final ext in cfg.sdkExtensions) {
        _line(buf, '  - $ext');
      }
    }

    _line(buf, 'command: ${cfg.command}');

    if (cfg.finishArgs.isNotEmpty) {
      _line(buf, '# Sandbox permissions — add or remove as your app requires.');
      _line(buf, 'finish-args:');
      for (final arg in cfg.finishArgs) {
        _line(buf, '  - $arg');
      }
    }

    _line(buf, 'modules:');

    // Extra modules (inline YAML or file paths).
    // Files are included verbatim with a 2-space indent so they can be
    // written as normal YAML lists rooted at the modules level.
    for (final modPath in cfg.extraModules) {
      final f = File(modPath);
      if (f.existsSync()) {
        final content = f.readAsStringSync().trimRight();
        for (final rawLine in content.split('\n')) {
          _line(buf, '  $rawLine');
        }
      } else {
        stderr.writeln('⚠  extra_modules: file not found: $modPath');
        _line(buf, '  - $modPath');
      }
    }

    // App module.
    _line(buf, '  - name: $appName');
    _line(buf, '    buildsystem: simple');
    _buildOptions(buf, appName);
    _buildCommands(buf, appName);
    _sources(buf);

    return buf.toString();
  }

  void _buildOptions(StringBuffer buf, String appName) {
    buf.writeln('    build-options:');

    if (hasFlutter) {
      buf.writeln('      arch:');
      buf.writeln('        x86_64:');
      buf.writeln('          env:');
      buf.writeln('            BUNDLE_PATH: build/linux/x64/release/bundle');
      buf.writeln('        aarch64:');
      buf.writeln('          env:');
      buf.writeln('            BUNDLE_PATH: build/linux/arm64/release/bundle');
    }

    final appendParts = <String>[];
    String? prependLdLib = cfg.prependLdLibraryPath;

    // Auto-detect llvm sdk-extension and add its paths.
    for (final ext in cfg.sdkExtensions) {
      final m = RegExp(r'llvm(\d+)').firstMatch(ext);
      if (m != null) {
        final ver = m.group(1)!;
        appendParts.add('/usr/lib/sdk/llvm$ver/bin');
        prependLdLib ??= '/usr/lib/sdk/llvm$ver/lib';
      }
    }
    if (hasFlutter) {
      // Flutter SDK is bundled into the build dir — add its bin to PATH.
      appendParts.add('/run/build/$appName/flutter/bin');
    }
    if (cfg.appendPath != null) appendParts.add(cfg.appendPath!);

    if (appendParts.isNotEmpty) {
      buf.writeln('      append-path: ${appendParts.join(':')}');
    }
    if (prependLdLib != null) {
      buf.writeln('      prepend-ld-library-path: $prependLdLib');
    }

    buf.writeln('      env:');
    if (hasFlutter) {
      buf.writeln('        PUB_CACHE: /run/build/$appName/.pub-cache');
    }
    for (final entry in cfg.env.entries) {
      buf.writeln('        ${entry.key}: ${entry.value}');
    }
  }

  void _buildCommands(StringBuffer buf, String appName) {
    buf.writeln('    # Build steps — review and customise for your project.');
    buf.writeln('    build-commands:');

    if (hasFlutter) {
      // Flutter cache stamp copies.
      final stamps = [
        'engine-dart-sdk.stamp',
        'material_fonts.stamp',
        'gradle_wrapper.stamp',
        'engine_stamp.stamp',
        'flutter_sdk.stamp',
        'font-subset.stamp',
        'linux-sdk.stamp',
      ];
      final versionFiles = {
        'engine-dart-sdk.stamp': 'engine.version',
        'material_fonts.stamp': 'material_fonts.version',
        'gradle_wrapper.stamp': 'gradle_wrapper.version',
        'engine_stamp.stamp': 'engine.version',
        'flutter_sdk.stamp': 'engine.version',
        'font-subset.stamp': 'engine.version',
        'linux-sdk.stamp': 'engine.version',
      };
      for (final stamp in stamps) {
        final src = versionFiles[stamp]!;
        buf.writeln(
            '      - cp flutter/bin/internal/$src flutter/bin/cache/$stamp');
      }

      buf
        ..writeln('      - setup-flutter.sh')
        ..writeln('      - flutter build linux --release --no-pub')
        ..writeln('      - mkdir -p /app/$appName')
        ..writeln('      - cp -r "\$BUNDLE_PATH"/. /app/$appName/')
        ..writeln(
            '      - install -Dm755 $outputRelDir/$appName-wrapper.sh /app/bin/$appName');
    } else {
      buf.writeln('      # TODO: add your build commands here');
    }

    // Asset installs using effective paths from config.
    final metainfoSrc = cfg.effectiveMetainfoPath();
    final metainfoDest = '/app/share/metainfo/${cfg.appId}.metainfo.xml';
    buf.writeln('      - install -Dm644 $metainfoSrc $metainfoDest');

    final desktopSrc = cfg.effectiveDesktopEntryPath();
    final desktopDest = '/app/share/applications/${cfg.appId}.desktop';
    buf.writeln('      - install -Dm644 $desktopSrc $desktopDest');

    for (final icon in cfg.effectiveIcons()) {
      final ext = icon.size == 'scalable' ? 'svg' : 'png';
      final iconDest =
          '/app/share/icons/hicolor/${icon.size}/apps/${cfg.appId}.$ext';
      buf.writeln('      - install -Dm644 ${icon.path} $iconDest');
    }
  }

  void _sources(StringBuffer buf) {
    buf.writeln(
        '    # Sources — do not remove __FLATPAK_TAG__ / __FLATPAK_COMMIT__.');
    buf.writeln('    sources:');

    // App git source with placeholders.
    buf.writeln('      - type: git');
    final url = resolvedRepoUrl ?? cfg.repoUrl;
    if (url != null) {
      buf.writeln('        url: $url');
    }
    buf.writeln('        tag: $tagPlaceholder');
    buf.writeln('        commit: $commitPlaceholder');
    buf.writeln('        disable-submodules: true');

    // Extra verbatim sources (e.g. arch-specific prebuilt archives).
    for (final src in cfg.extraSources) {
      _writeYamlMap(buf, src, indent: '      ');
    }

    // generated-sources.json reference (relative to manifest dir).
    buf.writeln(
        '      # "flutpak generate" injects patch sources after this line.');
    buf.writeln('      - ${p.basename(generatedSourcesPath)}');
  }

  /// Writes a Map as indented YAML key-value pairs with a leading `- ` on the
  /// first key (list item syntax).
  static void _writeYamlMap(StringBuffer buf, Map<String, dynamic> map,
      {required String indent}) {
    var first = true;
    for (final entry in map.entries) {
      final value = entry.value;
      final prefix = first ? '- ' : '  ';
      if (value is List) {
        buf.writeln('$indent$prefix${entry.key}:');
        for (final item in value) {
          buf.writeln('$indent    - $item');
        }
      } else {
        buf.writeln('$indent$prefix${entry.key}: $value');
      }
      first = false;
    }
  }

  static void _line(StringBuffer buf, String s) => buf.writeln(s);
}

/// Updates [tagPlaceholder] / [commitPlaceholder] in a manifest's raw YAML text.
///
/// If [tag] is null or empty, the `tag:` placeholder line is removed.
String patchManifestPlaceholders(
  String content, {
  required String commit,
  String? tag,
}) {
  var result = content;

  final hasTagPlaceholder = result.contains(tagPlaceholder);
  final hasCommitPlaceholder = result.contains(commitPlaceholder);

  if (hasTagPlaceholder || hasCommitPlaceholder) {
    // Fast path: manifest still has template placeholders.
    if (tag != null && tag.isNotEmpty) {
      result = result.replaceAll(tagPlaceholder, tag);
    } else {
      result = result.replaceAll(
        RegExp(r'[ \t]*tag:\s*' + RegExp.escape(tagPlaceholder) + r'\n?'),
        '',
      );
    }
    result = result.replaceAll(commitPlaceholder, commit);
  } else {
    // Manifest was previously pinned — placeholders are gone.
    // Locate the app source block by its unique `disable-submodules: true`
    // marker and re-pin tag/commit in-place.
    result = result.replaceFirstMapped(
      RegExp(
        r'(?:[ \t]*tag:\s+\S+\n)?([ \t]*)commit:\s+\S+(?=\n[ \t]*disable-submodules:)',
        multiLine: true,
      ),
      (m) {
        final indent = m.group(1)!;
        final tagLine =
            (tag != null && tag.isNotEmpty) ? '${indent}tag: $tag\n' : '';
        return '$tagLine${indent}commit: $commit';
      },
    );
  }

  return result;
}

/// Strips template-only guidance comments from [content] before writing the
/// generated manifest.
///
/// The template manifest contains human-readable hints (header block and
/// inline section labels) that are useful in the committed template but add
/// noise to the final flatpak-builder manifest in `generated/`. This function
/// must be called before [patchManifestPlaceholders] to prevent placeholder
/// strings inside comments from being replaced with commit SHAs.
String stripTemplateGuidance(String content) {
  var result = content;

  // Strip the multi-line guidance block that follows the "Generated by" line.
  result = result.replaceFirst(
    RegExp(
      '#\n'
      '# This is your editable TEMPLATE manifest[^\n]*\n'
      '# Run "flutpak generate"[^\n]*\n'
      '#\n'
      '# SAFE TO EDIT[^\n]*\n'
      '# DO NOT REMOVE[^\n]*\n'
      '# AUTO-INJECTED[^\n]*\n',
    ),
    '',
  );

  // Strip inline section guidance comments.
  for (final re in [
    RegExp(r'[ \t]*# Sandbox permissions[^\n]*\n'),
    RegExp(r'[ \t]*# Build steps — review[^\n]*\n'),
    RegExp(r'[ \t]*# Sources — do not remove[^\n]*\n'),
    RegExp(r'[ \t]*# "flutpak generate" injects patch sources[^\n]*\n'),
  ]) {
    result = result.replaceAll(re, '');
  }

  return result;
}

/// Injects [patches] as `type: patch` sources into [content] immediately after
/// the `generated-sources.json` reference line.
///
/// Patch files are expected to be copied to `generated/patches/` by the caller,
/// so paths are written as `patches/<basename>`. The `dest:` field is derived
/// from the resolved package version via [PatchEntry.dest].
///
/// Returns [content] unchanged when [patches] is empty or when the
/// `generated-sources.json` anchor line is not found.
///
/// [patchesDir] is the directory that will be copied to `generated/patches/`.
/// Patch paths in the manifest are written relative to that directory so the
/// subdirectory structure is preserved (e.g. `patches/subdir/foo.patch`).
String injectPatchSources(
  String content,
  List<PatchEntry> patches,
  String patchesDir,
) {
  if (patches.isEmpty) return content;

  final absPatchesDir = p.absolute(patchesDir);

  final buf = StringBuffer();
  for (final patch in patches) {
    final dest = patch.version != null ? patch.dest(patch.version!) : null;
    final relFromPatchesDir =
        p.relative(p.absolute(patch.path), from: absPatchesDir);
    final patchPath = 'patches/$relFromPatchesDir';

    if (patch.stripTrailingCr && dest != null) {
      final targetFile = _parsePatchTarget(patch.path);
      if (targetFile != null) {
        buf.writeln('      - type: shell');
        buf.writeln('        commands:');
        buf.writeln("          - sed -i 's/\\r//' $dest/$targetFile");
      }
    }

    buf.writeln('      - type: patch');
    if (dest != null) {
      buf.writeln('        dest: $dest');
    }
    buf.writeln('        path: $patchPath');
    if (patch.options.isNotEmpty) {
      buf.writeln('        options:');
      for (final opt in patch.options) {
        buf.writeln('          - $opt');
      }
    }
  }

  return content.replaceFirstMapped(
    RegExp(r'([ \t]*-[ \t]+generated-sources\.json\n)', multiLine: true),
    (m) => '${m.group(0)}${buf.toString()}',
  );
}

/// Reads the first `--- a/<path>` line of a unified diff and returns the
/// target file path with the leading `a/` stripped (i.e. the path after `-p1`
/// stripping). Returns null if the header is not found or the file cannot be read.
String? _parsePatchTarget(String patchPath) {
  try {
    for (final line in File(patchPath).readAsLinesSync()) {
      if (line.startsWith('--- ')) {
        final path = line.substring(4).trim();
        if (path == '/dev/null') return null;
        return path.startsWith('a/') ? path.substring(2) : path;
      }
    }
  } catch (_) {}
  return null;
}

/// Pins screenshot URLs in a metainfo XML file from `/main/` to [ref].
/// Replaces the entire `<screenshots>` block in [content] with one built
/// from [screenshots] config, using [repoSlug] and [ref] for URLs.
///
/// If [screenshots] is empty or [repoSlug] is empty the file is returned
/// unchanged.  Falls back to `main` when [ref] is empty.
String replaceMetainfoScreenshots(
  String content, {
  required List<ScreenshotConfig> screenshots,
  required String repoSlug,
  required String ref,
}) {
  if (screenshots.isEmpty || repoSlug.isEmpty) return content;
  final gitRef = ref.isNotEmpty ? ref : 'main';

  final buf = StringBuffer('  <screenshots>\n');
  var first = true;
  for (final s in screenshots) {
    final isDefault = s.default_ || first;
    final tag = isDefault ? '<screenshot type="default">' : '<screenshot>';
    buf.writeln('    $tag');
    buf.writeln(
        '      <image>https://raw.githubusercontent.com/$repoSlug/$gitRef/${s.path}</image>');
    buf.writeln('    </screenshot>');
    first = false;
  }
  buf.write('  </screenshots>');

  return content.replaceFirstMapped(
    RegExp(r'[ \t]*<screenshots>.*?</screenshots>', dotAll: true),
    (_) => buf.toString(),
  );
}

/// Updates the first `<release .../>` entry inside `<releases>` in a
/// metainfo XML file.
///
/// - Strips a leading `v` from [tag] (e.g. `v0.1.15` → `0.1.15`).
/// - Formats [date] as `YYYY-MM-DD`.
/// - Returns [content] unchanged if [tag] is empty or if no `<releases>`
///   section is present.
String patchMetainfoReleases(String content, String tag, DateTime date) {
  if (tag.isEmpty) return content;
  if (!content.contains('<releases>')) return content;

  final version = tag.startsWith('v') ? tag.substring(1) : tag;
  final dateStr =
      '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';

  return content.replaceFirstMapped(
    RegExp(r'(<release\s[^/]*/?>)', multiLine: true),
    (m) {
      final original = m.group(1)!;
      var updated = original.replaceFirst(
        RegExp('version\\s*=\\s*["\'][^"\']*["\']'),
        'version="$version"',
      );
      updated = updated.replaceFirst(
        RegExp('date\\s*=\\s*["\'][^"\']*["\']'),
        'date="$dateStr"',
      );
      return updated;
    },
  );
}
