import '../config.dart';

/// Generates a Flatpak application manifest YAML from [ManifestConfig].
///
/// Writes a human-readable manifest file using a structured template.
/// Multi-line build commands use YAML block scalar (`|`) notation.
class ManifestGenerator {
  final ManifestConfig cfg;

  /// Path to generated-sources.json relative to the project root.
  final String generatedSourcesPath;

  /// Directory path relative to the project source root used in install
  /// commands (e.g. `flatpak`). Defaults to `flatpak`.
  final String outputRelDir;

  /// Resolved git remote URL for the app source entry.
  final String? resolvedRepoUrl;

  /// Whether this project uses Flutter. When false, Flutter-specific build
  /// commands (cache stamps, flutter pub get, flutter build) are omitted and
  /// replaced with a TODO comment. Defaults to true for backward compatibility.
  final bool hasFlutter;

  /// Effective metainfo XML path passed from [FlatpakGenConfig].
  final String metainfoPath;

  /// Effective desktop entry path passed from [FlatpakGenConfig].
  final String desktopEntryPath;

  /// Effective icon list passed from [FlatpakGenConfig].
  final List<IconEntry> icons;

  /// Whether to emit `disable-submodules: true` in the git source entry.
  final bool disableSubmodules;

  ManifestGenerator({
    required this.cfg,
    required this.generatedSourcesPath,
    this.outputRelDir = 'flatpak',
    this.resolvedRepoUrl,
    this.hasFlutter = true,
    required this.metainfoPath,
    required this.desktopEntryPath,
    required this.icons,
    this.disableSubmodules = false,
  });

  /// Returns the manifest as a YAML string ready to write to disk.
  String generate() {
    final appName = cfg.appId.split('.').last;
    final effectiveExtensions = _effectiveSdkExtensions();
    final buf = StringBuffer();

    _line(buf, '# Generated by flutpak — https://github.com/o-murphy/flutpak');
    _line(buf, '#');
    _line(buf, '# This is your editable TEMPLATE manifest — commit it to git.');
    _line(buf,
        '# Run "flutpak generate" on every build to produce the final output in generated/.');
    _line(buf, '#');
    _line(buf,
        '# SAFE TO EDIT   finish-args, build-commands, build-options, sdk-extensions, modules');
    _line(buf,
        '# AUTO-INJECTED  tag, commit, modules, manifest.sources, generated-sources.json, and patches are set/appended by generate');
    _line(buf, 'app-id: ${cfg.appId}');
    _line(buf, 'runtime: org.freedesktop.Platform');
    _line(buf, "runtime-version: '${cfg.runtimeVersion}'");
    _line(buf, 'sdk: org.freedesktop.Sdk');

    if (effectiveExtensions.isNotEmpty) {
      _line(buf, 'sdk-extensions:');
      for (final ext in effectiveExtensions) {
        _line(buf, '  - $ext');
      }
    }

    _line(buf, 'command: ${cfg.command}');

    _line(buf, '# Sandbox permissions — review and adjust for your app.');
    _line(buf, 'finish-args:');
    const mandatoryFinishArgs = [
      '--share=ipc',
      '--socket=fallback-x11',
      '--socket=wayland',
      '--device=dri',
    ];
    final seen = <String>{};
    for (final arg in [...mandatoryFinishArgs, ...cfg.finishArgs]) {
      if (seen.add(arg)) _line(buf, '  - $arg');
    }

    _line(buf, 'modules:');

    // App module. modules are injected by `flutpak generate`.
    _line(buf, '  - name: $appName');
    _line(buf, '    buildsystem: simple');
    _buildOptions(buf, appName, effectiveExtensions);
    _buildCommands(buf, appName);
    _sources(buf);

    return buf.toString();
  }

  /// Returns [cfg.sdkExtensions] plus an auto-injected LLVM extension when
  /// [hasFlutter] is true and no llvm extension is already present.
  List<String> _effectiveSdkExtensions() {
    final exts = List<String>.from(cfg.sdkExtensions);
    if (hasFlutter && !exts.any((e) => e.contains('llvm'))) {
      exts.add(_inferLlvmExtension(cfg.runtimeVersion));
    }
    return exts;
  }

  /// Maps a Freedesktop SDK [runtimeVersion] to its bundled LLVM extension.
  /// Falls back to llvm20 (latest known) for unrecognised versions.
  static String _inferLlvmExtension(String runtimeVersion) {
    const map = {
      '23.08': 'org.freedesktop.Sdk.Extension.llvm17',
      '24.08': 'org.freedesktop.Sdk.Extension.llvm19',
      '25.08': 'org.freedesktop.Sdk.Extension.llvm20',
    };
    return map[runtimeVersion] ?? 'org.freedesktop.Sdk.Extension.llvm20';
  }

  void _buildOptions(
      StringBuffer buf, String appName, List<String> sdkExtensions) {
    buf.writeln('    build-options:');

    if (hasFlutter) {
      buf.writeln('      arch:');
      buf.writeln('        x86_64:');
      buf.writeln('          env:');
      buf.writeln('            BUNDLE_PATH: build/linux/x64/release/bundle');
      buf.writeln('        aarch64:');
      buf.writeln('          env:');
      buf.writeln('            BUNDLE_PATH: build/linux/arm64/release/bundle');
    }

    final appendParts = <String>[];
    String? prependLdLib = cfg.prependLdLibraryPath;

    // Auto-detect llvm sdk-extension and add its paths.
    for (final ext in sdkExtensions) {
      final m = RegExp(r'llvm(\d+)').firstMatch(ext);
      if (m != null) {
        final ver = m.group(1)!;
        appendParts.add('/usr/lib/sdk/llvm$ver/bin');
        prependLdLib ??= '/usr/lib/sdk/llvm$ver/lib';
      }
    }
    if (hasFlutter) {
      // Flutter SDK is bundled into the build dir — add its bin to PATH.
      appendParts.add('/run/build/$appName/flutter/bin');
    }
    if (cfg.appendPath != null) appendParts.add(cfg.appendPath!);

    if (appendParts.isNotEmpty) {
      buf.writeln('      append-path: ${appendParts.join(':')}');
    }
    if (prependLdLib != null) {
      buf.writeln('      prepend-ld-library-path: $prependLdLib');
    }

    buf.writeln('      env:');
    if (hasFlutter) {
      buf.writeln('        PUB_CACHE: /run/build/$appName/.pub-cache');
    }
    for (final entry in cfg.env.entries) {
      buf.writeln('        ${entry.key}: ${entry.value}');
    }
  }

  void _buildCommands(StringBuffer buf, String appName) {
    buf.writeln('    # Build steps — review and customise for your project.');
    buf.writeln('    build-commands:');

    if (hasFlutter) {
      // Flutter cache stamp copies.
      final stamps = [
        'engine-dart-sdk.stamp',
        'material_fonts.stamp',
        'gradle_wrapper.stamp',
        'engine_stamp.stamp',
        'flutter_sdk.stamp',
        'font-subset.stamp',
        'linux-sdk.stamp',
      ];
      final versionFiles = {
        'engine-dart-sdk.stamp': 'engine.version',
        'material_fonts.stamp': 'material_fonts.version',
        'gradle_wrapper.stamp': 'gradle_wrapper.version',
        'engine_stamp.stamp': 'engine.version',
        'flutter_sdk.stamp': 'engine.version',
        'font-subset.stamp': 'engine.version',
        'linux-sdk.stamp': 'engine.version',
      };
      for (final stamp in stamps) {
        final src = versionFiles[stamp]!;
        // Use $FLATPAK_BUILDER_BUILDDIR (always the module root, regardless of
        // whether subdir: is set) so these commands work correctly when the
        // Flutter project lives in a subdirectory of the git repo.
        buf.writeln(
            '      - cp \$FLATPAK_BUILDER_BUILDDIR/flutter/bin/internal/$src'
            ' \$FLATPAK_BUILDER_BUILDDIR/flutter/bin/cache/$stamp');
      }

      buf
        ..writeln('      - flutter pub get --offline')
        ..writeln('      - flutter build linux --release --no-pub')
        ..writeln('      - mkdir -p /app/$appName')
        ..writeln('      - cp -r "\$BUNDLE_PATH"/. /app/$appName/')
        ..writeln(
            '      - install -Dm755 $outputRelDir/$appName-wrapper.sh /app/bin/${cfg.command}');
    } else {
      buf.writeln('      # TODO: add your build commands here');
    }

    // Asset installs using effective paths from config.
    final metainfoDest = '/app/share/metainfo/${cfg.appId}.metainfo.xml';
    buf.writeln('      - install -Dm644 $metainfoPath $metainfoDest');

    final desktopDest = '/app/share/applications/${cfg.appId}.desktop';
    buf.writeln('      - install -Dm644 $desktopEntryPath $desktopDest');

    for (final icon in icons) {
      final ext = icon.size == 'scalable' ? 'svg' : 'png';
      final iconDest =
          '/app/share/icons/hicolor/${icon.size}/apps/${cfg.appId}.$ext';
      buf.writeln('      - install -Dm644 ${icon.path} $iconDest');
    }
  }

  void _sources(StringBuffer buf) {
    buf.writeln('    sources:');

    buf.writeln('      - type: git');
    final url = resolvedRepoUrl;
    if (url != null) {
      buf.writeln('        url: $url');
    }
    if (disableSubmodules) buf.writeln('        disable-submodules: true');
    // tag, commit, manifest.sources, generated-sources.json, and patches are
    // set/appended by `flutpak generate` via yaml_edit.
  }

  static void _line(StringBuffer buf, String s) => buf.writeln(s);
}

/// Strips template-only guidance comments from [content] before writing the
/// generated manifest.
///
/// The template manifest contains human-readable hints (header block and
/// inline section labels) that are useful in the committed template but add
/// noise to the final flatpak-builder manifest in `generated/`.
String stripTemplateGuidance(String content) {
  var result = content;

  // Strip the multi-line guidance block that follows the "Generated by" line.
  result = result.replaceFirst(
    RegExp(
      '#\n'
      '# This is your editable TEMPLATE manifest[^\n]*\n'
      '# Run "flutpak generate"[^\n]*\n'
      '#\n'
      '# SAFE TO EDIT[^\n]*\n'
      '# AUTO-INJECTED[^\n]*\n',
    ),
    '',
  );

  // Strip inline section guidance comments.
  for (final re in [
    RegExp(r'[ \t]*# Sandbox permissions[^\n]*\n'),
    RegExp(r'[ \t]*# Build steps — review[^\n]*\n'),
  ]) {
    result = result.replaceAll(re, '');
  }

  return result;
}

/// Converts [content] (a unified diff) to CRLF line endings.
///
/// Normalises any pre-existing `\r\n` sequences first to avoid doubling.
String convertPatchToCrlf(String content) =>
    content.replaceAll('\r\n', '\n').replaceAll('\n', '\r\n');

/// Converts [content] (a unified diff) to LF line endings.
String convertPatchToLf(String content) => content.replaceAll('\r\n', '\n');

/// Returns true if [content] contains at least one bare `\n` not preceded by
/// `\r`, i.e. the string has LF line endings.
bool patchHasLfLineEndings(String content) =>
    RegExp(r'(?<!\r)\n').hasMatch(content);

/// Pins screenshot URLs in a metainfo XML file from `/main/` to [ref].
/// Replaces the entire `<screenshots>` block in [content] with one built
/// from [screenshots] config, using [repoSlug] and [ref] for URLs.
///
/// If [screenshots] is empty or [repoSlug] is empty the file is returned
/// unchanged.  Falls back to `main` when [ref] is empty.
String replaceMetainfoScreenshots(
  String content, {
  required List<ScreenshotConfig> screenshots,
  required String repoSlug,
  required String ref,
}) {
  if (screenshots.isEmpty || repoSlug.isEmpty) return content;
  final gitRef = ref.isNotEmpty ? ref : 'main';

  final buf = StringBuffer('  <screenshots>\n');
  var first = true;
  for (final s in screenshots) {
    final isDefault = s.default_ || first;
    final tag = isDefault ? '<screenshot type="default">' : '<screenshot>';
    buf.writeln('    $tag');
    buf.writeln(
        '      <image>https://raw.githubusercontent.com/$repoSlug/$gitRef/${s.path}</image>');
    buf.writeln('    </screenshot>');
    first = false;
  }
  buf.write('  </screenshots>');

  return content.replaceFirstMapped(
    RegExp(r'[ \t]*<screenshots>.*?</screenshots>', dotAll: true),
    (_) => buf.toString(),
  );
}

/// Updates the first `<release .../>` entry inside `<releases>` in a
/// metainfo XML file.
///
/// - Strips a leading `v` from [tag] (e.g. `v0.1.15` → `0.1.15`).
/// - Formats [date] as `YYYY-MM-DD`.
/// - Returns [content] unchanged if [tag] is empty or if no `<releases>`
///   section is present.
String patchMetainfoReleases(String content, String tag, DateTime date) {
  if (tag.isEmpty) return content;
  if (!content.contains('<releases>')) return content;

  final version = tag.startsWith('v') ? tag.substring(1) : tag;
  final dateStr =
      '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';

  return content.replaceFirstMapped(
    RegExp(r'(<release\s[^/]*/?>)', multiLine: true),
    (m) {
      final original = m.group(1)!;
      var updated = original.replaceFirst(
        RegExp('version\\s*=\\s*["\'][^"\']*["\']'),
        'version="$version"',
      );
      updated = updated.replaceFirst(
        RegExp('date\\s*=\\s*["\'][^"\']*["\']'),
        'date="$dateStr"',
      );
      return updated;
    },
  );
}
