import '../config.dart';

/// Generates an AppStream metainfo XML file from [MetainfoConfig].
///
/// The generated file is a valid starting point for Flathub submission.
/// Fill in the OARS block via https://hughsie.github.io/oars/ before submitting.
class MetainfoGenerator {
  final String appId;
  final MetainfoConfig cfg;

  /// Version string for the initial <release> entry (e.g. "0.1.15").
  /// Leading `v` is stripped automatically.
  final String? version;

  /// Date for the initial <release> entry. Defaults to today (UTC).
  final DateTime? releaseDate;

  MetainfoGenerator({
    required this.appId,
    required this.cfg,
    this.version,
    this.releaseDate,
  });

  String generate() {
    final buf = StringBuffer();
    buf.writeln('<?xml version="1.0" encoding="UTF-8"?>');
    buf.writeln('<!-- Generated by flutpak — https://github.com/o-murphy/flutpak -->');
    buf.writeln('<component type="desktop-application">');
    buf.writeln('  <id>$appId</id>');
    buf.writeln('  <metadata_license>MIT</metadata_license>');
    buf.writeln('  <project_license>MIT</project_license>');
    buf.writeln('  <name>${_esc(cfg.name!)}</name>');
    buf.writeln('  <summary>${_esc(cfg.summary!)}</summary>');

    if (cfg.description != null && cfg.description!.isNotEmpty) {
      buf.writeln('  <description>');
      for (final para in _splitParagraphs(cfg.description!)) {
        buf.writeln('    <p>${_esc(para)}</p>');
      }
      buf.writeln('  </description>');
    }

    if (cfg.categories.isNotEmpty) {
      buf.writeln('  <categories>');
      for (final cat in cfg.categories) {
        buf.writeln('    <category>$cat</category>');
      }
      buf.writeln('  </categories>');
    }

    if (cfg.keywords.isNotEmpty) {
      buf.writeln('  <keywords>');
      for (final kw in cfg.keywords) {
        buf.writeln('    <keyword>${_esc(kw)}</keyword>');
      }
      buf.writeln('  </keywords>');
    }

    _writeUrls(buf);
    _writeLaunchable(buf);
    _writeScreenshots(buf);
    _writeReleases(buf);
    _writeContentRating(buf);

    buf.writeln('</component>');
    return buf.toString();
  }

  void _writeUrls(StringBuffer buf) {
    final u = cfg.url;
    if (u == null) return;
    if (u.homepage != null) {
      buf.writeln('  <url type="homepage">${u.homepage}</url>');
    }
    if (u.bugtracker != null) {
      buf.writeln('  <url type="bugtracker">${u.bugtracker}</url>');
    }
    if (u.donation != null) {
      buf.writeln('  <url type="donation">${u.donation}</url>');
    }
  }

  void _writeLaunchable(StringBuffer buf) {
    buf.writeln('  <launchable type="desktop-id">$appId.desktop</launchable>');
  }

  void _writeScreenshots(StringBuffer buf) {
    if (cfg.screenshots.isEmpty) return;
    buf.writeln('  <screenshots>');
    var first = true;
    for (final s in cfg.screenshots) {
      final isDefault = s.default_ || first;
      if (isDefault) {
        buf.writeln('    <screenshot type="default">');
      } else {
        buf.writeln('    <screenshot>');
      }
      // URL uses /main/ as placeholder — flutpak prepare pins it to tag/commit.
      final repoSlug = cfg.repoSlug ?? '';
      final url = repoSlug.isNotEmpty
          ? 'https://raw.githubusercontent.com/$repoSlug/main/${s.path}'
          : 'https://raw.githubusercontent.com/__REPO__/main/${s.path}';
      buf.writeln('      <image>$url</image>');
      buf.writeln('    </screenshot>');
      first = false;
    }
    buf.writeln('  </screenshots>');
  }

  void _writeReleases(StringBuffer buf) {
    final ver = version != null
        ? (version!.startsWith('v') ? version!.substring(1) : version!)
        : '0.0.1';
    final date = releaseDate ?? DateTime.now().toUtc();
    final dateStr =
        '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';
    buf.writeln('  <releases>');
    buf.writeln('    <release version="$ver" date="$dateStr"/>');
    buf.writeln('  </releases>');
  }

  void _writeContentRating(StringBuffer buf) {
    buf.writeln(
        '  <!-- Fill in OARS ratings via https://hughsie.github.io/oars/ -->');
    buf.writeln('  <content_rating type="${cfg.contentRating}"/>');
  }

  static String _esc(String s) => s
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;');

  static List<String> _splitParagraphs(String text) => text
      .split(RegExp(r'\n{2,}'))
      .map((p) => p.trim())
      .where((p) => p.isNotEmpty)
      .toList();
}
