#!/usr/bin/env dart
/// Reads version from pubspec.yaml and writes lib/src/version.dart.
/// Run this whenever you bump the version in pubspec.yaml:
///   dart run tool/update_version.dart
library;

import 'dart:io';
import 'package:yaml/yaml.dart';

void main() {
  final pubspec = File('pubspec.yaml');
  if (!pubspec.existsSync()) {
    stderr.writeln('pubspec.yaml not found — run from the package root.');
    exit(1);
  }

  final yaml = loadYaml(pubspec.readAsStringSync()) as YamlMap;
  final version = yaml['version']?.toString();
  if (version == null || version.isEmpty) {
    stderr.writeln('No version field found in pubspec.yaml.');
    exit(1);
  }

  final output = File('lib/src/version.dart');
  output.writeAsStringSync(
    '// Generated by tool/update_version.dart — do not edit by hand.\n'
    '// Run `dart run tool/update_version.dart` after bumping pubspec.yaml.\n'
    "const String packageVersion = '$version';\n",
  );

  stdout.writeln('Updated ${output.path} → $version');
}
